### ISSUE TITLE
Error from "get_intersection()"

### ISSUE THREAD

**Issue by jaquol** [3DGenomes/tadbit#113]
I was getting the following error when using the "get_intersection()" function:

```
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/fdg/scripts/pipeline_hic/map_process_merge.py", line 97, in <module>
    get_intersection(outfiles[0], outfiles[1], final_output, verbose = True)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/pytadbit/mapping/mapper.py", line 48, in get_intersection
    locale.setlocale(locale.LC_ALL, '.'.join(locale.getdefaultlocale()))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```
I found a solution [here](https://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8/19961403#19961403)

**Comment by fransua** [comment]
Hi @jaquol ,
thanks for finding this problem and its solution :)
I will integrate it into TADbit.
