### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by Lila14** [3DGenomes/TADbit#157]
I installed TADbit without MCL. The output from test_all.py is as follows:
```
PYTHON SIDE
-----------
..............FF...

C SIDE
------
rm -f testset *.o *.gcda *.gcno *.gcov gmon.out analysis.txt \
	callgrind.out.* cache.txt
gcc -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage   -c -o tadbit.o ../tadbit.c
gcc -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage    testset.c tadbit.o  `pkg-config --libs glib-2.0` -lpthread -lm -o testset
gtester --verbose --keep-going testset
TEST: testset... (pid=25881)
  /ll:                                                                 OK
  /enforce_symmetry:                                                   OK
  /tadbit:                                                             OK
lilmatlilmatlilmatlilmatPASS: testset
.
======================================================================
FAIL: test_15_3d_modelling (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 556, in test_15_3d_modelling
    [0, 2, 2, 3, 4])
AssertionError: Lists differ: [0.0, 1.0, 2.0, 3.0, 3.0] != [0, 2, 2, 3, 4]

First differing element 1:
1.0
2

- [0.0, 1.0, 2.0, 3.0, 3.0]
+ [0, 2, 2, 3, 4]

======================================================================
FAIL: test_16_models_stats (__main__.TestTadbit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 642, in test_16_models_stats
    self.assertEqual([15, 16], model.inaccessible_particles(1000))
AssertionError: Lists differ: [15, 16] != [11, 12, 15, 16]

First differing element 0:
15
11

Second list contains 2 additional elements.
First extra element 2:
15

- [15, 16]
+ [11, 12, 15, 16]

----------------------------------------------------------------------
Ran 20 tests in 47.427s

FAILED (failures=2)
```

**Comment by fransua** [comment]
Hi @Lila14 
this issue is probably due to a different version of IMP check issue https://github.com/3DGenomes/TADbit/issues/112
you might be able to fix it by installing the last version of IMP from conda for example. However even like this the result might be slightly different depending on the machine, and thus fail some tests. We should implement a better set of tests to account for this.

In any case if you downloaded TADbit from github, you can check here: https://travis-ci.org/3DGenomes/TADbit that the current version passes the tests and it should also be ok on your current installation.

let me know if this helps (which version of IMP have you installed?)

thanks

**Comment by Lila14** [comment]
My IMP version is 2.6.2.

**Comment by fransua** [comment]
Issue merged to https://github.com/3DGenomes/TADbit/issues/184
