### ISSUE TITLE
IMPoptimizer issue

### ISSUE THREAD

**Issue by Lila14** [3DGenomes/TADbit#159]
I wrote a script based on the documentation:

```
path = "chr22_1kb_tadbit.tsv"
# initiate a chromosome object that will store all Hi-C data and analysis
my_chrom = Chromosome(name="chr22", centromere_search=True, species="Homo sapiens", assembly="NCBI37")

# load Hi-C data
my_chrom.add_experiment("GM12878", cell_type="wild type", exp_type="Hi-C", identifier="GM12878", project="test", hic_data=path, resolution=1000)

exp = my_chrom.experiments[0]

exp.load_hic_data(path)
optimizer = IMPoptimizer(exp, 100, 200, n_models=50, n_keep=25)
```

The output was:

```
/usr/lib64/python2.7/site-packages/pytadbit/parsers/hic_parser.py:194: UserWarning: WARNING: found header
  warn('WARNING: found header')
/usr/lib64/python2.7/site-packages/pytadbit/parsers/hic_parser.py:228: UserWarning: WARNING: non integer values
  warn('WARNING: non integer values')
Traceback (most recent call last):
  File "tadbit.py", line 16, in <module>
    optimizer = IMPoptimizer(exp, 100, 200, n_models=50, n_keep=25)
  File "/usr/lib64/python2.7/site-packages/pytadbit/imp/impoptimizer.py", line 48, in __init__
    self.values, zeros) = experiment._sub_experiment_zscore(start, end)
  File "/usr/lib64/python2.7/site-packages/pytadbit/experiment.py", line 899, in _sub_experiment_zscore
    if not self._normalization.startswith('visibility'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by fransua** [comment]
Hi @Lila14 ,
sorry for the late reply.
Yes,it seems that there is a bug here. Can you try to normalize before running the optimization?

    exp.normalize_hic()

cheers

francois
