### ISSUE TITLE
Issue with parsing mapping files

### ISSUE THREAD

**Issue by apaytuvi** [3DGenomes/TADbit#163]
Hi @fransua ,

With the last version of TADbit, cloned from the master branch yesterday from GitHub, I have a problem with the following command:

```
>>> parse_map(mapped_r1, mapped_r2, out_file1=reads1, out_file2=reads2, genome_seq=genome_seq, re_name="MboI", verbose=True, ncpus=10)
Searching and mapping RE sites to the reference genome
Found 6709728 RE sites
Loading read1
loading file: ./01_95401_read1/95401_1.fq_full_1-25.map
loading file: ./01_95401_read1/95401_1.fq_full_1-50.map
loading file: ./01_95401_read1/95401_1.fq_full_1-75.map
loading file: ./01_95401_read1/95401_1.fq_full_1-100.map
Merge sort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pytadbit/parsers/map_parser.py", line 143, in parse_map
    tmp_name = tmp_files[0]
IndexError: list index out of range
```

Previous commands are:

```
import pytadbit
from pytadbit.mapping.mapper import full_mapping

mapped_r1 = full_mapping("/Sharing/genomes/mus_musculus/release81/Mus_musculus.GRCm38.dna.toplevel.gem",
                         "../FASTQ_trimmed_q15/Trimmed_files/merged/95401_1.fq.gz",
                         "./01_95401_read1",
                         windows=((1,25), (1,50), (1,75),(1,100)),
                         frag_map=False, nthreads=10, clean=True,
                         temp_dir="./tmp")

mapped_r2 = full_mapping("/Sharing/genomes/mus_musculus/release81/Mus_musculus.GRCm38.dna.toplevel.gem",
                         "../FASTQ_trimmed_q15/Trimmed_files/merged/95401_2.fq.gz",
                         "./01_95401_read2",
                         windows=((1,25), (1,50), (1,75),(1,100)),
                         frag_map=False, nthreads=10, clean=True,
                         temp_dir="./tmp")

from pytadbit.parsers.map_parser    import parse_map
from pytadbit.parsers.genome_parser import parse_fasta

genome_seq = parse_fasta("/Sharing/genomes/mus_musculus/release81/Mus_musculus.GRCm38.dna.toplevel.fa")

from pytadbit.utils.file_handling import mkdir

mkdir("./02_95401_parsed_reads/")

reads1 = "./02_95401_parsed_reads/read1.tsv"
reads2 = "./02_95401_parsed_reads/read2.tsv"
```

**Comment by fransua** [comment]
Hi,
it can be an issue with the generation of the file: Mus_musculus.GRCm38.dna.toplevel.gem
can you check if the chromosome names in the file: Mus_musculus.GRCm38.dna.toplevel.fa
and see if they coincide with the chromosome names in the mapped files 95401_1.fq_full_1-25.map

**Comment by apaytuvi** [comment]
Hi @fransua 

chromosome names in `Mus_musculus.GRCm38.dna.toplevel.fa` are the same than in `95401_1.fq_full_1-25.map`.

**Comment by fransua** [comment]
good!
thanks
