### ISSUE TITLE
problem finding components

### ISSUE THREAD

**Issue by apaytuvi** [3DGenomes/TADbit#167]
I get

```
Traceback (most recent call last):
  File "/Synology/003-Andreu-PhD/HERRERA_01/20170111/analysis_TADbit/commands_matrix.py", line 155, in <module>
    main()
  File "/Synology/003-Andreu-PhD/HERRERA_01/20170111/analysis_TADbit/commands_matrix.py", line 144, in main
    hic_data.find_compartments(chrms=chr_, savefig=args.output+"/"+name+"_compartments", savedata=args.output+"/"+name+"_compartments/"+chr_+".txt", vmin=-0.10, vmax=0.10)
  File "/usr/lib64/python2.7/site-packages/pytadbit/hic_data.py", line 769, in find_compartments
    self._apply_metric(cmprts, sec, rich_in_A, how=how)
  File "/usr/lib64/python2.7/site-packages/pytadbit/hic_data.py", line 854, in _apply_metric
    for j in xrange(beg1, end1) if not j in self.bads]
KeyError: 3114
```

when calling:

```
hic_data.find_compartments(savefig=args.output+"/"+name+"_compartments", savedata=args.output+"/"+name+"_compartments.txt", vmin=-0.10, vmax=0.10)
```

**Comment by fransua** [comment]
Hi @apaytuvi 
there is probably a problem in the definition of the hic_data object.
Can you send me more about your script? :)

**Comment by apaytuvi** [comment]
Hi @fransua , thanks for this reply!

I have a file like this:

```
chr1    0-1000000       1320    99      19      23      29      30      19      16      29      10      12      19      16      1       11      6       10      5       4       3       4       7       6       6       9       5       6       0       4       3       4       7       9       8       1       2
       9       2       3       4       8       5       9       2       7       2       1       5       4       5       3       4       2       1       3
       2       5       0       3       3       1       6       1       5       2       4       2       4       0       5       3       3       2       1
       2       1       2       1       0       3       1       5       0       1       2       1       2       2       1       1       0       1       1
       0       1       0       0       1       0       1       1       0       3       0       0       3       0       0       0       2       0       2
       2       4       3       1       2       0       2       0       0       1       0       0       0       0       0       0       0       0       0
       0       0       0       0       0       0       0       0       0       0       0       19      5       2       3       0       1       0       0
       3       0       0       0       2       1       0       1       0       0       0       2       2       0       0       1       1       2       0
       0       0       2       1       1       2       0       0       1       0       0       0       0       0       0       2       0       0       0
       2       1       0       1       1       1       0       1       0       0       0       1       0       1       1       1       3       0       0
       2       1       1       0       0       0       3       1       0       0       4       0       0       0       0       5       0       48      2
       0       1       7       2       0       1       0       1       0       3       0       0       0       0       0       0       0       1       1
       1       1       0       0       0       4       0       0       0       0       0       3       1       0       0       0       0       5       0
       0       0       0       0       0       0       0       0       0       1       1       1       1       1       1       1       0       2       0
       0       0       0       0       1       0       1       1       0       0       0       1       0       0       0       0       0       1       0
       0       1       2       3       0       0       1       0       1       0       1       0       0       0       0       1       4       3       1
       0       0       8       0       1       0       0       2       0       0       1       0       0   [...]
```

and I load it using:

`hic_data = read_matrix(file, resolution=args.resolution)`
