### ISSUE TITLE
quality_plot: Variable-length reads after cutadapt error

### ISSUE THREAD

**Issue by rysterzhu** [3DGenomes/TADbit#228]
Traceback (most recent call last):
  File "quality_plot.py", line 21, in <module>
    quality_plot(idir + "/" + j, nreads=1000000, r_enz='MboI', savefig=wdir+"/"+j.replace("fastq.gz","png"), paired=True)
  File "/home/test/anaconda2/lib/python2.7/site-packages/pytadbit/utils/fastq_utils.py", line 159, in quality_plot
    yerr=errorquals, ecolor='orange')
  File "/home/test/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1845, in inner
    return func(ax, *args, **kwargs)
  File "/home/test/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 3173, in errorbar
    self.add_line(data_line)
  File "/home/test/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 1932, in add_line
    self._update_line_limits(line)
  File "/home/test/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 1954, in _update_line_limits
    path = line.get_path()
  File "/home/test/anaconda2/lib/python2.7/site-packages/matplotlib/lines.py", line 951, in get_path
    self.recache()
  File "/home/test/anaconda2/lib/python2.7/site-packages/matplotlib/lines.py", line 661, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/lib/stride_tricks.py", line 249, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/lib/stride_tricks.py", line 184, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape

**Comment by rysterzhu** [comment]
raw fastq data passed, but after cutadapt the error occur
cutadapt -j 8 --trim-n -q 25,25 -m 75 -a AGATCGGAAGAGC -A AGATCGGAAGAGC

**Comment by fransua** [comment]
it can be that the function expects reads with the same lengths... I will check. On the other side, I don't if cutadapt has an option for this.
