### ISSUE TITLE
plot_distance_vs_interactions issue

### ISSUE THREAD

**Issue by dawe** [3DGenomes/TADbit#279]
Hi again, 
During the tests I'm running, I've slipped into this error from `plot_distance_vs_interactions` function

```
 ddi = plot_distance_vs_interactions(reads, savefig='DDI.png', axe = ax,  max_diff=10000, resolution=1000000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dcittaro/.local/lib/python2.7/site-packages/pytadbit/mapping/analyze.py", line 430, in plot_distance_vs_interactions
    for k in xrange(max(dist_intr[diff]) - diff)]
ValueError: max() arg is an empty sequence
```

Any hint on how to tackle this is appreciated.

**Comment by fransua** [comment]
Hi @dawe 
sorry for the late repply.
I guess that the problem here is that there is not data point in a given range. Perhaps you can play with the `min_diff` and `max_diff` parameters to focus on the range of distances where you do have data.

We will try to make TADbit robust to this case in the future.

thanks for reporting
