### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by DonStephano** [3DGenomes/TADbit#289]
Hi,
maybe someone can help me. I'd like to install TADbit and created a Conda environment and also successfully installed the dependencies. During the installation of TADbit I was confronted with the following error:

`Checking dependencies...
Traceback (most recent call last):
  File "setup.py", line 228, in <module>
    exit(main())
  File "setup.py", line 163, in main
    print('\n\nFOUND changes:\n' + git_status + '.')
TypeError: can only concatenate str (not "bytes") to str`

So, I'm not sure what is wrong? Did I miss something? Scipy, numpy, matplotlib, pysam are installed, also jupyter and sra-tools.
Thx a lot

**Comment by david-castillo** [comment]
Hi,
First, verify that you are using python2 (python --version).
If so, can you do a git diff in your tadbit folder? It seems that you are getting an array of bytes from subprocess instead of a string, which is more likely to happen in python3 from what I read.

Regards
David
