### ISSUE TITLE
Unknown error with process

### ISSUE THREAD

**Issue by poflawless** [3DGenomes/TADbit#352]
Hello,
After I installed the TADdyn, I wanna try the test data and run with this:

python2 test_TADdyn_on_Sox2.py

whereas the error logs shows like this:

Optimizing 300 particles
  num scale     kbending        maxdist lowfreq upfreq  dcutoff correlation
WARNING: not all models produced: step 1, nmodels=100
  1   0.01      0               150     -3      0       100    0.477
  2   0.01      0               150     -3      1       100    0.5725
  3   0.01      0               150     -3      2       100    0.4501
  4   0.01      0               150     -3      3       100    0.2003
  5   0.01      0               150     -2      0       100    0.5026
  6   0.01      0               150     -2      1       100    0.5823
  7   0.01      0               150     -2      2       100    0.4504
  8   0.01      0               150     -2      3       100    0.2003
  9   0.01      0               150     -1      0       100    0.6097
  10  0.01      0               150     -1      1       100    0.6358
  11  0.01      0               150     -1      2       100    0.4508
  12  0.01      0               150     -1      3       100    0.2
  13  0.01      0               150     0       0       100    0.6122
  14  0.01      0               150     0       1       100    0.6392
  15  0.01      0               150     0       2       100    0.452
  16  0.01      0               150     0       3       100    0.2026
  17  0.01      0               200     -3      0       100    0.25
  18  0.01      0               200     -3      1       100    0.552
  19  0.01      0               200     -3      2       100    0.4392
  20  0.01      0               200     -3      3       100    0.2033
  21  0.01      0               200     -2      0       100    0.3219
  22  0.01      0               200     -2      1       100    0.5702
  23  0.01      0               200     -2      2       100    0.4384
............................................................................................................
    94  0.01      0               400     0       1       100    0.4153
  95  0.01      0               400     0       2       100    0.2748
WARNING: this is an empty shell, no data here.
  96  0.01      0               400     0       3       100    0.1998
Succesfully generated tadbit initial conformation

Unknown error with process
Unknown error with process
Unknown error with process
Unknown error with process
Unknown error with process
Unknown error with process
Models analysis:
0 - Loading the models
1 - Z-score plots
DONE
2 - Snapshots
Traceback (most recent call last):
  File "/NetScratch/JingA/tools/Chr_simulation/TADdyn/test/Sox2/test_TADdyn_on_Sox2.py", line 91, in <module>
    sm.view_models(models=[int(stage*100*100)], tool="plot", savefig="./Results/Snapshots/Snapshot_trajectory_1_timepoint_%d.png" % int(stage*100))
  File "/NetScratch/JingA/Miniconda3/envs/Chr_simulation/lib/python2.7/site-packages/pytadbit/modelling/structuralmodels.py", line 2165, in view_models
    self[model]['x'], self[model]['y'], self[model]['z']))
  File "/NetScratch/JingA/Miniconda3/envs/Chr_simulation/lib/python2.7/site-packages/pytadbit/modelling/structuralmodels.py", line 156, in __getitem__
    return self.__models[nam]
KeyError: 10000

Did anyone know the reason and solution?

**Comment by david-castillo** [comment]
Hi,

I checked it and the problem seems to come from one of the last updates (https://github.com/3DGenomes/TADdyn/blob/20f1ea8becf6de77cbe5a1e78c8dac545e9d0874/taddyn/modelling/lammps_modelling.py#L697) . 
Mainly the initial conformations should be returned at the beginning the dictionary of models (in the keys 0 to nkeep) but they are not, and that broke the test.
I need to fix that.

David
