### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by rekado** [3DGenomes/TADbit#371]
We're building tadbit 1.0.1 with Python 3.9 and there are a few test failures:

```
/gnu/store/p5fgysbcnnp8b1d91mrvjvababmczga0-python-3.9.6/lib/python3.9/_collections_abc.py:768: MatplotlibDeprecationWarning: 
The mpl_toolkits.legacy_colorbar rcparam was deprecated in Matplotlib 3.4 and will be removed two minor releases later.
  self[key]
/gnu/store/g3rwkw6fx1wp8rsafsk9lh54bgzyg322-tadbit-1.0.1/lib/python3.9/site-packages/pytadbit/utils/extraviews.py:22: MatplotlibDeprecationWarning: 
The mpl_toolkits.legacy_colorbar rcparam was deprecated in Matplotlib 3.4 and will be removed two minor releases later.
  plt.rcParams["mpl_toolkits.legacy_colorbar"] = False
...........PYTHON SIDE
-----------
  SKIPPING: 'ListSingletonContainer' object has no attribute 'get_particle'
  SKIPPING: 'ListSingletonContainer' object has no attribute 'get_particle'
  SKIPPING: 'ListSingletonContainer' object has no attribute 'get_particle'
WARNING: no optimization done yet
E  SKIPPING: 'ListSingletonContainer' object has no attribute 'get_particle'
E......rm -f testset *.o *.gcda *.gcno *.gcov gmon.out analysis.txt \
	callgrind.out.* cache.txt
gcc -fcommon -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage   -c -o tadbit.o ../tadbit.c
gcc -fcommon -I.. `pkg-config --cflags glib-2.0` -g -pg -Wall -std=gnu99 -O0 -fstrict-aliasing -fprofile-arcs -ftest-coverage    testset.c tadbit.o  `pkg-config --libs glib-2.0` -lpthread -lm -o testset
gtester --verbose --keep-going testset

** (gtester:3140): WARNING **: 14:52:42.400: Deprecated: Since GLib 2.62, gtester and gtester-report are deprecated. Port to TAP.
TEST: testset... (pid=3141)
  /ll:                                                                 OK
  /enforce_symmetry:                                                   OK
  /tadbit:                                                             OK
lilmatlilmatlilmatlilmatPASS: testset
.
======================================================================
ERROR: test_12_3d_modelling_optimization (__main__.TestTadbit)
quick test to generate 3D coordinates from 3? simple models???
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-tadbit-1.0.1.drv-0/source/test/test_all.py", line 442, in test_12_3d_modelling_optimization
    self.assertEqual([round(config[i], 4) for i in list(config.keys()) if not type(i) is str],
AttributeError: 'NoneType' object has no attribute 'keys'

======================================================================
ERROR: test_13_3d_modelling_centroid (__main__.TestTadbit)
quick test to generate 3D coordinates from 3? simple models???
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gnu/store/p5fgysbcnnp8b1d91mrvjvababmczga0-python-3.9.6/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/gnu/store/g3rwkw6fx1wp8rsafsk9lh54bgzyg322-tadbit-1.0.1/lib/python3.9/site-packages/pytadbit/modelling/imp_modelling.py", line 318, in generate_IMPmodel
    p = model['particles'].get_particle(i)
AttributeError: 'ListSingletonContainer' object has no attribute 'get_particle'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/guix-build-tadbit-1.0.1.drv-0/source/test/test_all.py", line 470, in test_13_3d_modelling_centroid
    models = exp.model_region(51, 71, n_models=40, n_keep=25,
  File "/gnu/store/g3rwkw6fx1wp8rsafsk9lh54bgzyg322-tadbit-1.0.1/lib/python3.9/site-packages/pytadbit/experiment.py", line 919, in model_region
    return generate_3d_models(zscores, self.resolution, nloci,
  File "/gnu/store/g3rwkw6fx1wp8rsafsk9lh54bgzyg322-tadbit-1.0.1/lib/python3.9/site-packages/pytadbit/modelling/imp_modelling.py", line 199, in generate_3d_models
    models, bad_models = multi_process_model_generation(
  File "/gnu/store/g3rwkw6fx1wp8rsafsk9lh54bgzyg322-tadbit-1.0.1/lib/python3.9/site-packages/pytadbit/modelling/imp_modelling.py", line 272, in multi_process_model_generation
    results.append((rand_init, jobs[rand_init].get()))
  File "/gnu/store/p5fgysbcnnp8b1d91mrvjvababmczga0-python-3.9.6/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'ListSingletonContainer' object has no attribute 'get_particle'

----------------------------------------------------------------------
Ran 20 tests in 48.642s

FAILED (errors=2)
```

**Comment by rekado** [comment]
The tests don't fail with the latest commit 5c4c1ddaadfbaf7e6edc58173e46d801093bdc9b.  For Guix I'll upgrade to that commit instead of the latest tagged release.
