### ISSUE TITLE
TADbit model

### ISSUE THREAD

**Issue by yangqihang1230** [3DGenomes/TADbit#394]
"I installed TADbit but couldn't export the model function. I can run the test set normally."

optional arguments:
  -h, --help            show this help message and exit

AVAILABLE PROGRAMS:
  {map,parse,filter,describe,clean,normalize,bin,export,import,merge,segment}
    map                 Map Hi-C reads and organize results in an output
                        working directory
    parse               Parse mapped Hi-C reads and get the intersection
    filter              Filter parsed Hi-C reads and get valid pair of reads
                        to work with
    describe            Describe jobs and results in a given working directory
    clean               Delete jobs and results of a given list of jobids in a
                        given directories
    normalize           normalize Hi-C data and generates array of biases
    bin                 bin Hi-C data into matrices
    export              export Hi-C data to other formats
    import              import Hi-C data to TADbit toy BAM
    merge               load two working directories with different Hi-C data
                        samples and merges them into a new working directory
                        generating some statistics
    segment             Finds TAD or compartment segmentation in Hi-C data.

**Comment by fransua** [comment]
Hi,
the most probable cause for this issue is that you have not installed the IMP library: https://github.com/salilab/imp

**Comment by yangqihang1230** [comment]
Thank you very much for your reply. The model is now displaying correctly, but a new error has occurred. I'm not sure if it's caused by the format of my input file.


(py37) mawei@bioinformatics:/home/Mawei/yqh/3Dgenome/TADbit$ tadbit model --workdir model__test1 --input_matrix 500.abc --noX --optimize --reso 20000 --nmodels 5 --nkeep 5 --exp_type Hi-C --force --matrix_beg 1
     o Loading Hi-C matrix
     o WARNING: reusing existing folder,                                     please check if you need to remove
Traceback (most recent call last):
  File "/home/data2/yqh/conda/envs/py37/bin/tadbit", line 170, in <module>
    main(sys.argv)
  File "/home/data2/yqh/conda/envs/py37/bin/tadbit", line 167, in main
    args.func(args)
  File "/home/data2/yqh/conda/envs/py37/lib/python3.7/site-packages/pytadbit/tools/tadbit_model.py", line 738, in run
    opts.end - opts.beg))
TypeError: %d format: a number is required, not NoneType


This is the sample format of my input file.
# CRM chr1 64444167
# chr1:1-10 resolution:20000
# MASKED 
1 1 93.282519
2 2 73.714816
2 3 36.596588
2 4 33.871353
3 5 21.741614
3 6 17.209513
3 7 16.437257
3 8 15.460301
3 9 11.267053
3 10 15.363264

**Comment by fransua** [comment]
hi,
sorry for the late reply. Perhaps just add the end coordinate too (which would be, I guess, the size of you matrix).
