### ISSUE TITLE
do something clever when parsing empty SAM file

### ISSUE THREAD

**Issue by fransua** [3DGenomes/tadbit#77]
line 103 of mapper.py

**Comment by MarcoDiS** [comment]
Traceback (most recent call last):
  File "/project/devel/mstefano/Project_A_thaliana/HiC_maps/Grob2014/SRR1197490/03_uniquely_mapped_reads_SRR1197490.py", line 62, in <module>
    verbose=True)
  File "/home/devel/mstefano/py27/lib/python2.7/site-packages/pytadbit/parsers/sam_parser.py", line 97, in parse_sam
    next_re    = frag_piece[idx]
IndexError: list index out of range
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

**Comment by fransua** [comment]
It was a problem specific to reads mapped at the very end of a chromosome, with unmatched nucleotides dangling futher its end. It is now fixed.
